config/routes.rb
CodetvNginx::Application.routes.draw do
  resources :entries

  root :to => "home#index"

  ### Begin RailsThemes basic generated routes ###

  # Routes to RailsThemes Theme Example markup:
  namespace :railsthemes do
    match '/' => 'railsthemes#index', :via => [:get]
    match '/:action', :controller => :railsthemes, :via => [:get, :post]
  end

  # This is magical routing for errors (instead of using the static markup in
  # public/*.html)
  match '/403' => 'railsthemes_errors#403_forbidden', :via => [:get]
  match '/404' => 'railsthemes_errors#404_not_found', :via => [:get]
  match '/500' => 'railsthemes_errors#500_internal_server_error', :via => [:get]

  ### End RailsThemes basic generated routes ###
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :mood
  accepts_nested_attributes_for :mood
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body, :mood_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= simple_form_for(@entry) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body
    = f.association :mood

  .form-actions
    = f.button :submit

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/index.html.haml
%h1 Code School Journal

%table
  %tr
    %th Date
    %th Title
    %th Body
    %th Mood
    %th
    %th
    %th

  - @entries.each do |entry|
    %tr
      %td
        = time_ago_in_words(entry.created_at)
        ago
      %td= entry.title
      %td= entry.body
      %td= entry.mood.name
      %td= link_to 'Show', entry
      %td= link_to 'Edit', edit_entry_path(entry)
      %td= link_to 'Destroy', entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.haml
%h1 New Journal Entry

= render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @entry.title
%p
  %b Body:
  = @entry.body
%p
  %b Mood:
  = @entry.mood.name

= link_to 'Edit', edit_entry_path(@entry)
\|
= link_to 'Back', entries_path